version: "3"
services:
  registry:
    image: registry:2.7
    container_name: registry
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.cr-http.entrypoints: "web"
      traefik.http.routers.cr-http.rule: "Host(`cr.mrh.io`)"
      traefik.http.routers.cr-http.middlewares: "cr-https"
      traefik.http.middlewares.cr-https.redirectscheme.scheme: "https"

      traefik.http.routers.cr.rule: "Host(`cr.mrh.io`)"
      traefik.http.routers.cr.entryPoints: "websecure"
      traefik.http.routers.cr.service: "cr"
      traefik.http.services.cr.loadbalancer.server.port: "5000"
      traefik.http.routers.cr.tls: true
      traefik.http.routers.cr.tls.certresolver: "letsencrypt"