---
version: "3"

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_DATABASE
    volumes:
      - bookstack_data:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
    labels:
      traefik.enable: "true"
      traefik.http.routers.bookstack.entrypoints: web
      traefik.http.routers.bookstack.rule: "Host(`bookstack`)"
      traefik.http.routers.bookstack.service: bookstack
      traefik.http.services.bookstack.loadbalancer.server.port: 6875
      
      
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD
      - TZ=Europe/London
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - bookstack_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  bookstack_config:
  bookstack_data:

networks:
  traefik-swarm:
     external: true
