version: "3.3"

services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      # - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      # - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    environment:
      - ADMIN_USER_EMAIL
      - ADMIN_USER_NAME
      - ADMIN_USER_PWD
      - BASE_URL
      - SECRET_KEY_BASE
    labels:
      traefik.enable: "true"
      traefik.http.routers.plausible-http.entrypoints: "web"
      traefik.http.routers.plausible-http.rule: "Host(`plausible.mrh.io`)"
      traefik.http.routers.plausible-http.middlewares: "plausible-https"
      traefik.http.middlewares.plausible-https.redirectscheme.scheme: "https"

      traefik.http.routers.plausible.rule: "Host(`plausible.mrh.io`)"
      traefik.http.routers.plausible.entryPoints: "websecure"
      traefik.http.routers.plausible.service: "plausible"
      traefik.http.services.plausible.loadbalancer.server.port: "80"
      traefik.http.routers.plausible.tls: true
      traefik.http.routers.plausible.tls.certresolver: "letsencrypt"

volumes:
  db-data:
  event-data:
  geoip:
