version: '3.3'

services:
  wordpress_db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - wordpress_db:/var/lib/mysql

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:6.1.1-fpm-alpine
    restart: always
    networks:
      - traefik-swarm
      - default
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
    volumes:
      - wordpress:/var/www/html
    labels:
      traefik.enable: "true"
      traefik.http.routers.pedalgeeks-wp-http.entrypoints: "web"
      traefik.http.routers.pedalgeeks-wp-http.rule: "Host(`pedalgeeks.co`)"
      traefik.http.routers.pedalgeeks-wp-http.middlewares: "pedalgeeks-wp-https"
      traefik.http.middlewares.pedalgeeks-wp-https.redirectscheme.scheme: "https"

      traefik.http.routers.pedalgeeks-wp.rule: "Host(`pedalgeeks.co`)"
      traefik.http.routers.pedalgeeks-wp.entryPoints: "websecure"
      traefik.http.routers.pedalgeeks-wp.service: "pedalgeeks-wp"
      traefik.http.services.pedalgeeks-wp.loadbalancer.server.port: "80"
      traefik.http.routers.pedalgeeks-wp.tls: "true"
      traefik.http.routers.pedalgeeks-wp.tls.certresolver: "letsencrypt"


  mediawiki:
    image: mediawiki:1.39.0
    restart: always
    networks:
      - traefik-swarm
      - default
    links:
      - database
    volumes:
      - mediawiki_images:/var/www/html/images
      - mediawiki_extensions:/var/www/html/extensions
    configs:
      - source: pedalgeeks-LocalSettings.php
        target: /var/www/html/LocalSettings.php
    labels:
      traefik.enable: "true"
      traefik.http.routers.pedalgeeks-wiki-http.entrypoints: "web"
      traefik.http.routers.pedalgeeks-wiki-http.rule: "Host(`wiki.pedalgeeks.co`)"
      traefik.http.routers.pedalgeeks-wiki-http.middlewares: "pedalgeeks-wiki-https"
      traefik.http.middlewares.pedalgeeks-wiki-https.redirectscheme.scheme: "https"

      traefik.http.routers.pedalgeeks-wiki.rule: "Host(`wiki.pedalgeeks.co`)"
      traefik.http.routers.pedalgeeks-wiki.entryPoints: "websecure"
      traefik.http.routers.pedalgeeks-wiki.service: "pedalgeeks-wiki"
      traefik.http.services.pedalgeeks-wiki.loadbalancer.server.port: "80"
      traefik.http.routers.pedalgeeks-wiki.tls: "true"
      traefik.http.routers.pedalgeeks-wiki.tls.certresolver: "letsencrypt"

  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - pedalgeeks_mediawiki_db:/var/lib/mysql

volumes:
  wordpress:
  mediawiki_images:
  mediawiki_extensions:
  pedalgeeks_mediawiki_db:
  wordpress_db:

networks:
  traefik-swarm:
    external: true

configs:
  pedalgeeks-LocalSettings.php:
    external: true
