version: '3.3'

services:
  mediawiki:
    image: mediawiki:1.39.0
    restart: always
    networks:
      - traefik-swarm
      - default
    links:
      - database
    volumes:
      - mediawiki_images:/var/www/html/images
      - mediawiki_extensions:/var/www/html/extensions
    configs:
      - source: pedalgeeks-LocalSettings.php
        target: /var/www/html/LocalSettings.php
    labels:
      traefik.enable: "true"
      traefik.http.routers.pedalgeeks-wiki-http.entrypoints: "web"
      traefik.http.routers.pedalgeeks-wiki-http.rule: "Host(`wiki.pedalgeeks.co`)"
      traefik.http.routers.pedalgeeks-wiki-http.middlewares: "pedalgeeks-wiki-https"
      traefik.http.middlewares.pedalgeeks-wiki-https.redirectscheme.scheme: "https"

      traefik.http.routers.pedalgeeks-wiki.rule: "Host(`wiki.pedalgeeks.co`)"
      traefik.http.routers.pedalgeeks-wiki.entryPoints: "websecure"
      traefik.http.routers.pedalgeeks-wiki.service: "pedalgeeks-wiki"
      traefik.http.services.pedalgeeks-wiki.loadbalancer.server.port: "80"
      traefik.http.routers.pedalgeeks-wiki.tls: "true"
      traefik.http.routers.pedalgeeks-wiki.tls.certresolver: "letsencrypt"

  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - pedalgeeks_mediawiki_db:/var/lib/mysql

volumes:
  mediawiki_images:
  mediawiki_extensions:
  pedalgeeks_mediawiki_db:
  
networks:
  traefik-swarm:
    external: true
    
configs:
  pedalgeeks-LocalSettings.php:
    external: true
