version: "3"
 
services:
  grist:
    image: gristlabs/grist
    environment:
      - GRIST_SESSION_SECRET
      - GRIST_DEFAULT_EMAIL
      - APP_HOME_URL=http://grist
    networks:
      - traefik-swarm
      - default
    volumes:
      - grist_data:/persist
    labels:
      traefik.enable: "true"
      traefik.http.routers.grist.entrypoints: web
      traefik.http.routers.grist.rule: "Host(`grist`)"
      traefik.http.routers.grist.service: grist
      traefik.http.services.grist.loadbalancer.server.port: 8484
      
volumes:
  grist_data:

networks:
  traefik-swarm:
    external: true
