version: "3"
 
services:
  nocodb:
    image: nocodb/nocodb:latest
    networks:
      - traefik-swarm
      - default
    volumes:
      - nocodb_data:/usr/app/data/
  labels:
      traefik.enable: "true"
      traefik.http.routers.nocodb.entrypoints: web
      traefik.http.routers.nocodb.rule: "Host(`nocodb`)"
      traefik.http.routers.nocodb.service: nocodb
      traefik.http.services.nocodb.loadbalancer.server.port: 8080

  server:
    image: baserow/baserow:1.13.1
    environment:
      - BASEROW_PUBLIC_URL=http://baserow
    networks:
      - traefik-swarm
      - default
    volumes:
      - baserow_data:/baserow/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.baserow.entrypoints: web
      traefik.http.routers.baserow.rule: "Host(`baserow`)"
      traefik.http.routers.baserow.service: baserow
      traefik.http.services.baserow.loadbalancer.server.port: 80

  grist:
    image: gristlabs/grist
    environment:
      - GRIST_SESSION_SECRET
      - GRIST_DEFAULT_EMAIL
      - APP_HOME_URL=http://grist
    networks:
      - traefik-swarm
      - default
    volumes:
      - grist_data:/persist
    labels:
      traefik.enable: "true"
      traefik.http.routers.grist.entrypoints: web
      traefik.http.routers.grist.rule: "Host(`grist`)"
      traefik.http.routers.grist.service: grist
      traefik.http.services.grist.loadbalancer.server.port: 8484
      
volumes:
  baserow_data:
  grist_data:
  nocodb_data:

networks:
  traefik-swarm:
    external: true
