version: '3.1'

services:

  httpd:
    image: aphelionz/lakeboone
    restart: unless-stopped
    networks:
      - default
      - traefik-swarm
    labels:
      traefik.enable: "true"
      traefik.http.routers.lakeboone-http.entrypoints: "web"
      traefik.http.routers.lakeboone-http.rule: "Host(`lakeboone.mrh.io`)"
      traefik.http.routers.lakeboone-http.middlewares: "lakeboone"
      traefik.http.middlewares.lakeboone.redirectscheme.scheme: "https"

      traefik.http.routers.lakeboone.rule: "Host(`lakeboone.mrh.io`)"
      traefik.http.routers.lakeboone.entryPoints: "websecure"
      traefik.http.routers.lakeboone.service: "lakeboone"
      traefik.http.services.lakeboone.loadbalancer.server.port: "3000"
      traefik.http.routers.lakeboone.tls: "true"
      traefik.http.routers.lakeboone.tls.certresolver: "letsencrypt"
    configs:
      - source: lakeboone-env-local
        target: /home/node/app/.env.local

networks:
  traefik-swarm:
    external: true
