#-------------------------------------------
#  Docker Compose
# @RobLandry
# Repo : https://github.com/LycheeOrg/Lychee-Laravel-Docker
#-------------------------------------------

version: '3'

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    expose: 
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    volumes:
      - conf:/conf
      - uploads:/uploads
      - sym:/sym
    networks:
      - default
      - traefik
    environment:
      #- PUID=1000
      #- PGID=1000
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=UTC
      #- APP_NAME=Laravel
      #- APP_ENV=local
      #- APP_DEBUG=true
      #- APP_URL=http://localhost
      #- LOG_CHANNEL=stack
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      #- DB_DROP_CLEAR_TABLES_ON_ROLLBACK=false
      #- DB_OLD_LYCHEE_PREFIX=''
      #- BROADCAST_DRIVER=log
      #- CACHE_DRIVER=file
      #- SESSION_DRIVER=file
      #- SESSION_LIFETIME=120
      #- QUEUE_DRIVER=sync
      #- SECURITY_HEADER_HSTS_ENABLE=false
      #- REDIS_HOST=127.0.0.1
      #- REDIS_PASSWORD=null
      #- REDIS_PORT=6379
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_ENCRYPTION=null
      #- PUSHER_APP_ID=''
      #- PUSHER_APP_KEY=''
      #- PUSHER_APP_SECRET=''
      #- PUSHER_APP_CLUSTER=mt1
      - STARTUP_DELAY=30
    restart: unless-stopped
    depends_on:
      - lychee_db
    labels:
      traefik.enable: "true"
      traefik.http.routers.lychee-http.entrypoints: "web"
      traefik.http.routers.lychee-http.rule: "Host(`archive.jonsarkin.com`)"
      traefik.http.routers.lychee-http.middlewares: "lychee-https"
      traefik.http.middlewares.lychee-https.redirectscheme.scheme: "https"

      traefik.http.routers.lychee.rule: "Host(`archive.jonsarkin.com`)"
      traefik.http.routers.lychee.entryPoints: "websecure"
      traefik.http.routers.lychee.service: "lychee"
      traefik.http.services.lychee.loadbalancer.server.port: "80"
      traefik.http.routers.lychee.tls: true
      traefik.http.routers.lychee.tls.certresolver: "letsencrypt"
      
networks:
  traefik:
    external: true

volumes:
  mysql:
  sym:
  uploads:
  conf:
