version: '3.3'

services:

  chrony:
    image: cturra/ntp
    restart: unless-stopped
    networks:
      - traefik-swarm
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=0
      - NTP_SERVERS=clock.uregina.ca,ntp1a.versadns.com
      - NOCLIENTLOG=true
    labels:
      traefik.enable: "true"
      traefik.udp.routers.ntp.entrypoints: ntp
      traefik.udp.routers.ntp.service: ntp
      traefik.udp.services.ntp.loadbalancer.server.port: 123

networks:
  traefik-swarm:
    external: true
