---
version: "3.1"

services:
  mediagoblin:
   images: mtlynch/mediagoblin
   networks:
     - traefik-swarm
     - default
   labels:
     traefik.enable: "true"
     traefik.http.routers.mediagoblin-http.entrypoints: "web"
     traefik.http.routers.mediagoblin-http.rule: "Host(`media.mrh.io`)"
     traefik.http.routers.mediagoblin-http.middlewares: "mediagoblin-https"
     traefik.http.middlewares.mediagoblin-https.redirectscheme.scheme: "https"

     traefik.http.routers.mediagoblin.rule: "Host(`media.mrh.io`)"
     traefik.http.routers.mediagoblin.entryPoints: "websecure"
     traefik.http.routers.mediagoblin.service: "pedalgeeks-wp"
     traefik.http.services.mediagoblin.loadbalancer.server.port: "6543"
     traefik.http.routers.mediagoblin.tls: "true"
     traefik.http.routers.mediagoblin.tls.certresolver: "letsencrypt"

networks:
  traefik-swarm:
    external: true
