version: "3.7"
services:
  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 3000:3000
    restart: always
    networks:
      - traefik-swarm
      - default
    deploy:
      placement:
        constraints:
          - node.labels.metrics == true
    volumes:
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    deploy:
      mode: global
      labels:
        prometheus-job: node_exporter
        prometheus-port: 9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'

  prometheus:
    image: prom/prometheus
    user: root
    networks:
      traefik-swarm:
      default:
        aliases:
          - prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    deploy:
      placement:
        constraints:
          - node.labels.metrics == true

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    networks:
      - traefik-swarm
      - default
    ports:
      - 8081:8080
    deploy:
      mode: global
      labels:
        prometheus-job: cadvisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    command: -docker_only

volumes:
  grafana_data:

configs:
  prometheus.yml:
    external: true

networks:
  traefik-swarm:
    external: true